name: Frontend CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    # Sätt working directory till frontend mappen
    defaults:
      run:
        working-directory: ./frontend
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22'  # Matcha din Node version från package.json
        cache: 'npm'
        cache-dependency-path: 'frontend/package-lock.json'
    
    - name: Install dependencies
      run: npm install --legacy-peer-deps # Installs even with conflicts.
    
    - name: Run lint
      run: npm run lint
      continue-on-error: true
    
    # Använd test:run istället för test för CI
    - name: Run tests
      run: npm run test:run
      env:
        CI: true
    
    - name: Build app
      run: npm run build
    
    - name: Upload build files
      uses: actions/upload-artifact@v4
      with:
        name: build-files
        path: frontend/dist/

  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Download build files
      uses: actions/download-artifact@v4
      with:
        name: build-files
        path: dist/
    
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist
